name: 'Open API Specification Lint action'
description: 'Runs Swagger validation on your OAS JSON or YAML file. Supports Swagger 2.0 or OpenAPI 3.0 format'
inputs:
  args:
    description: 'Swagger-cli command arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    "INPUT_ARG": "${{ inputs.args }}"
