name: 'Swagger-cli'
description: 'Runs Swagger cli command'
inputs:
  command:
    description: 'Swagger-cli command arguments'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
